Repository TakoBoutIt/tacoboutit-frontend, pull requests merged in 2019-12, with the labels that each got.

#7 Add dependencies for maps, permissions, location, and constants
  package-lock.json
  package.json
Labels: FE, Phase 1

#38 Add RestaurantCard, add styles for card, create mock data
  App.js
  RestaurantCard.js
  mockRestaurants.js
  package-lock.json
  package.json
Labels: FE, Phase 2, enhancement

#40 Searchbar
  .gitignore
  App.js
  App.test.js
  assets/007-search.png
  assets/fonts/SignPainter-HouseScript.ttf
  package-lock.json
  package.json
  src/components/RestaurantCard/RestaurantCard.js
  src/components/RestaurantCard/RestaurantCard.test.js
  src/components/TacoSearch/TacoSearch.js
  src/components/TacoSearch/TacoSearch.test.js
Labels: FE, Phase 2

#42 Nav bar
  App.js
  assets/home.png
  assets/home.svg
  assets/taco.png
  package-lock.json
  package.json
Labels: FE, Phase 2, enhancement

#44 Implement flatlist for scrolling of our restaurant cards
  App.js
  mockRestaurants.js
Labels: FE, enhancement

#46 Add basic modal on click of restaurant card
  App.js
  src/components/RestaurantCard/RestaurantCard.js
Labels: FE, Phase 2, enhancement

#48 Early fetch test
  App.js
  mockRestaurants.js
  src/apiCalls.js
  src/components/RestaurantCard/RestaurantCard.js
  src/components/TacoSearch/TacoSearch.js
Labels: FE, Phase 2, enhancement

#50 Splash page
  App.js
  assets/fonts/Molle-Regular.ttf
  src/components/SplashPage/SplashPage.js
  src/components/SplashPage/SplashPage.test.js
Labels: FE, Phase 2, enhancement
