Repository TakoBoutIt/tacoboutit-frontend, pull requests merged in 2020-01, with the labels that each got.

#51 Restaurant page
  App.js
  src/components/RestaurantPage/RestaurantPage.js
  src/components/RestaurantPage/RestaurantPage.test.js
Labels: FE, enhancement, help wanted

#53 Add tacos
  App.js
  assets/call-answer.png
  assets/check-mark.png
  src/apiCalls.js
  src/components/AddTacoButton/AddTacoButton.js
  src/components/AddTacoButton/AddTacoButton.test.js
  src/components/RestaurantPage/RestaurantPage.js
  src/components/TacoCard/TacoCard.js
  src/components/TacoCard/TacoCard.test.js
Labels: FE, Phase 3, enhancement, help wanted

#55 Addtaco modal
  src/components/AddTacoButton/AddTacoButton.js
  src/components/RestaurantPage/RestaurantPage.js
Labels: FE, enhancement

#58 Setup enzyme, test AddTacoButton
  App.test.js
  __snapshots__/App.test.js.snap
  package-lock.json
  package.json
  src/components/AddTacoButton/AddTacoButton.js
  src/components/AddTacoButton/AddTacoButton.test.js
  src/setupTests.js
Labels: testing

#61 Testing methods
  .gitignore
  mockRestaurants.js
  src/apiCalls.js
  src/apiCalls.test.js
  src/components/AddTacoButton/AddTacoButton.test.js
  src/components/RestaurantCard/RestaurantCard.test.js
  src/components/RestaurantCard/__snapshots__/RestaurantCard.test.js.snap
  src/components/TacoCard/TacoCard.test.js
  src/components/TacoSearch/TacoSearch.test.js
Labels: testing

#68 Testing reviews
  App.js
  src/apiCalls.test.js
  src/components/AddReviewForm/AddReviewForm.js
  src/components/AddReviewForm/AddReviewForm.test.js
  src/components/AddReviewForm/__snapshots__/AddReviewForm.test.js.snap
  src/components/AddTacoButton/AddTacoButton.js
  src/components/RestaurantPage/RestaurantPage.test.js
  src/components/RestaurantPage/__snapshots__/RestaurantPage.test.js.snap
  src/components/ReviewCard/ReviewCard.js
  src/components/ReviewCard/ReviewCard.test.js
  src/components/ReviewCard/__snapshots__/ReviewCard.test.js.snap
  src/components/ReviewsPage/ReviewsPage.js
  src/components/ReviewsPage/ReviewsPage.test.js
  src/components/ReviewsPage/__snapshots__/ReviewsPage.test.js.snap
Labels: testing

#70 Hide icebox components
  App.js
  src/components/AddReviewForm/AddReviewForm.js
Labels: FE

#77 Update testing post review
  App.js
  App.test.js
  __snapshots__/App.test.js.snap
  package.json
  src/apiCalls.test.js
  src/components/AddReviewForm/AddReviewForm.test.js
  src/components/AddReviewForm/__snapshots__/AddReviewForm.test.js.snap
  src/components/ReviewsPage/ReviewsPage.test.js
Labels: FE, testing

#81 Reviewcard styling
  src/components/AddReviewForm/AddReviewForm.js
  src/components/AddReviewForm/__snapshots__/AddReviewForm.test.js.snap
  src/components/RestaurantPage/__snapshots__/RestaurantPage.test.js.snap
  src/components/ReviewCard/ReviewCard.js
  src/components/ReviewCard/__snapshots__/ReviewCard.test.js.snap
  src/components/ReviewsPage/ReviewsPage.js
Labels: FE, enhancement

#86 New taco add review error
  App.js
  App.test.js
  src/components/AddReviewForm/AddReviewForm.js
  src/components/AddReviewForm/AddReviewForm.test.js
Labels: FE, Phase 3, enhancement, testing

#87 Delete unused imports
  App.js
  src/apiCalls.js
  src/components/AddReviewForm/AddReviewForm.js
  src/components/AddTacoButton/AddTacoButton.js
  src/components/RestaurantCard/RestaurantCard.js
  src/components/RestaurantPage/RestaurantPage.js
  src/components/ReviewsPage/ReviewsPage.js
  src/components/SplashPage/SplashPage.js
  src/components/TacoSearch/TacoSearch.js
Labels: FE, formatting

#88 Readme
  README.md
  src/apiCalls.js
  src/apiCalls.test.js
Labels: BE, FE, Phase 3, documentation, enhancement, testing
